FROM amazoncorretto:22

# 빌드 시 인자를 받기 위한 ARG 설정
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG JWT_SECRET_KEY
ARG JWT_ACCESS_TOKEN_EXPIRATION_TIME
ARG JWT_REFRESH_TOKEN_EXPIRATION_TIME
ARG AWS_S3_BUCKET
ARG AWS_REGION
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG IMP_API_KEY
ARG IMP_SECRET_KEY

# 환경 변수 설정
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV JWT_ACCESS_TOKEN_EXPIRATION_TIME=$JWT_ACCESS_TOKEN_EXPIRATION_TIME
ENV JWT_REFRESH_TOKEN_EXPIRATION_TIME=$JWT_REFRESH_TOKEN_EXPIRATION_TIME
ENV AWS_S3_BUCKET=$AWS_S3_BUCKET
ENV AWS_REGION=$AWS_REGION
ENV AWS_ACCESS_KEY=$AWS_ACCESS_KEY
ENV AWS_SECRET_KEY=$AWS_SECRET_KEY
ENV IMP_API_KEY=$IMP_API_KEY
ENV IMP_SECRET_KEY=$IMP_SECRET_KEY

COPY build/libs/*.jar app.jar

ENTRYPOINT ["java", "-Duser.timezone=Asia/Seoul", \
    "-Dspring.datasource.url=${SPRING_DATASOURCE_URL}", \
    "-Dspring.datasource.username=${SPRING_DATASOURCE_USERNAME}", \
    "-Dspring.datasource.password=${SPRING_DATASOURCE_PASSWORD}", \
    "-Dspring.redis.host=${REDIS_HOST}", \
    "-Dspring.redis.port=${REDIS_PORT}", \
    "-Djwt.secret=${JWT_SECRET_KEY}", \
    "-Djwt.access-token-expiration-time=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}", \
    "-Djwt.refresh-token-expiration-time=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}", \
    "-Daws.s3.bucket=${AWS_S3_BUCKET}", \
    "-Daws.region=${AWS_REGION}", \
    "-Daws.access=${AWS_ACCESS_KEY}", \
    "-Daws.secret=${AWS_SECRET_KEY}", \
    "-Dimp.api.key=${IMP_API_KEY}", \
    "-Dimp.api.secretKey=${IMP_SECRET_KEY}", \
    "-jar", "/app.jar"]
