spring:
  application:
    name: poomasi
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        hbm2ddl:
          jdbc_metadata_extraction_strategy: individually
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: account_email
            # - profile_nickname
            # - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize #카카오 로그인 화면
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

  token:
    storage:
      type: redis
    blacklist:
      type: redis

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}
  access: ${AWS_ACCESS_KEY}
  secret: ${AWS_SECRET_KEY}

imp:
  api:
    key: ${IMP_API_KEY}
    secretKey: ${IMP_SECRET_KEY}


naver:
  ocr:
    secret: ${NAVER_OCR_SECRET}
    invoke: ${NAVER_OCR_INVOKE}
    template: ${NAVER_OCR_TEMPLATE}
